export { Home } from './Home';
export { Services } from './Services';
export { AIIntegration } from './AIIntegration';
export { About } from './About';
export { Contact } from './Contact';
export { Privacy } from './Privacy';
export { Terms } from './Terms';
export { NotFound } from './NotFound';
export { Layout } from './Layout';
